apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: snake-game
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/CodeSagePath/snake-game.git'
    targetRevision: HEAD
    path: manifests
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
